### ISSUE TITLE
[优化] 本地化键名复用与优化

### ISSUE THREAD

**Issue by Seayay** [Heart-Fire-Project/midnight-soul-dp#1]
尽可能将天赋名称等**可以复用的**本地化键名多次复用。
- [x] 技能本地化键名复用
- [x] 天赋本地化键名复用
- [x] 地图本地化键名复用
- [x] 标题本地化键名复用
- [ ] #3

**Comment by Roser7419** [comment]
数据包部分制作完成

**Comment by Roser7419** [comment]
剩下的就是多语言更新，之后就用 #3 那个就行
