### ISSUE TITLE
[新功能] 表现分 及 本局最佳

### ISSUE THREAD

**Issue by Seayay** [Heart-Fire-Project/midnight-soul-dp#13]
> 大饼，估计要等正式版发布才有这个功能

> 灵感来源：黎明杀机

从四个方面判定玩家本局表现，并显示本局表现分最高的玩家，同时根据表现分增加玩家游戏等级（显示在统计数据内）

灵魂方：
- 目标：收集灵魂碎片。
- 逃生：保持存活。
- 援助：帮助其他灵魂。
- 无畏：和灵魂守卫者及他们的物件互动。

灵魂守卫者方：
- 凶残：使灵魂濒死或遭受攻击。
- 周旋：使灵魂放慢收集速度。
- 狩猎：灵魂死亡。
- 技巧：在技能、天赋生效后一段时间击中。

**Comment by Roser7419** [comment]
对不起，做不到
对于部分条件进行了修改
具体将在日后更新阐述

**Comment by Roser7419** [comment]
修改无畏，取消周旋/技巧

**Comment by Roser7419** [comment]
感动了
