### ISSUE TITLE
[优化] 离开碎片收集区域后立刻取消显示 Actionbar

### ISSUE THREAD

**Issue by LittleChest** [Heart-Fire-Project/midnight-soul-dp#14]
**描述这个 Bug**

> 描述的清楚、详细一点

离开碎片收集区域后立刻取消显示Actionbar

**如何复现此 Bug**

> 如果你不知道怎么复现，就写你触发之前干了什么

寻找一个碎片，疾跑经过它

**异常情况**

> 这个 Bug 会带来什么情况？如果你不知道，可以空着

由于Minecraft的默认淡出，会产生碎片收集范围很大的错觉

**屏幕截图**

> 如果可以，附带游戏截图是极好的

无

**Comment by Roser7419** [comment]
Early Access γ 实装
